# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e224801eb31044143435de5b635e9e3fee0ec7f5d0c7edb093ed498457d345cd25948c6377da3c65f092ca474318b0bc51c55bd20bcc6948a72baacf7323300d

test:
  secret_key_base: fc4c72e1e40c22755984f6891d0991650b1951b0131c01fdf43cc3b36a8bbc93936e9d6ec9fa53f6bffefc40743cbc4cc6e86cca0e65dce0637936846f3155d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
